#Application URL 
url = https://automationexercise.com/login
browser =chrome

#credentials 
#username =admin
#password = admin123


#ImplicitWait (in seconds) 
implicitWait = 2

#ExplicitWait (in seconds)
explicitWait = 30
